import { defineConfig } from "wxt";

const isPrOnlyBuild = process.env.DLENS_EXTENSION_VARIANT === "pr-only";

// Generated by scripts/generate-icons.mjs into public/icon/ (WXT copies public/ to the build root).
const ICONS = {
  16: "icon/16.png",
  32: "icon/32.png",
  48: "icon/48.png",
  96: "icon/96.png",
  128: "icon/128.png"
};

export default defineConfig({
  modules: ["@wxt-dev/module-react"],
  srcDir: ".",
  entrypointsDir: "entrypoints",
  manifest: {
    name: isPrOnlyBuild ? "DLens PR Mode" : "DLens v3",
    version: "0.3.8",
    description: isPrOnlyBuild
      ? "PR Evidence-only Threads capture client for DLens ingest-core."
      : "Thin Threads capture client for DLens ingest-core.",
    permissions: ["storage", "tabs", "activeTab", "sidePanel"],
    icons: ICONS,
    host_permissions: [
      "*://www.threads.net/*",
      "*://threads.net/*",
      "*://www.threads.com/*",
      "*://threads.com/*",
      "http://127.0.0.1/*",
      "http://localhost/*",
      "https://generativelanguage.googleapis.com/*",
      "https://api.openai.com/*",
      "https://api.anthropic.com/*"
    ],
    action: {
      default_title: isPrOnlyBuild ? "DLens PR Mode" : "DLens",
      default_icon: ICONS
    },
    side_panel: {
      default_path: "sidepanel/index.html"
    }
  }
});
